### ISSUE TITLE
Typo in last_update and wrong data type

### ISSUE THREAD

**Issue by madman-81** [Llocer/llocer_ocpi_json#1]
There is a typo in last_update (it's missing the "d") and the data type should be timestamp instead of number. See 15.4.1 in the documentation

https://github.com/Llocer/llocer_ocpi_json/blob/6a97ea089c02cab433d6f75eaeaf7353141076d4/src/main/resources/schema/client_info#L22-L24

Should be:
```
    "last_updated": {
      "$ref": "timestamp#"
    }
```

**Comment by Llocer** [comment]
Fixed

Thanks for your message.
